// www/src/pages/Root/Index.vue
<script setup lang="ts">
import { router } from "@inertiajs/vue3";

let props = defineProps<{
	time: string;
}>();

const handleClick = () => {
	const start = Date.now().toString();
	window["start"] = start;
	router.get("/");
	console.count("fetch" + start);
};

if (window.localStorage.getItem("start")) {
	const start = parseInt(window["start"]);
	const now = Date.now();
	const diff = now - start;
	if (diff < 10000) {
		router.get("/");
		console.count("fetch" + start);
	}
}
</script>

<template>
	<header></header>

	<main>
		<h1>Loaded: {{ props.time }}</h1>
		<button @click="handleClick">Loop it!</button>
	</main>
</template>

<style scoped>
a {
	display: block;
	margin-bottom: 0.25rem;
}
</style>

// www-svelte/src/pages/Root/Index.svelte
<script lang="ts">
	import { router } from "@inertiajs/svelte";
	import { writable } from "svelte/store";

	export let time: string;

	const start = writable(null);

	const count = writable(0);

	const handleClick = () => {
		count.set(0);
		const startTime = Date.now().toString();
		start.set(startTime);
		router.get("/");
	};

	router.on("success", (event) => {
		if ($start) {
			count.set($count + 1);
			const now = Date.now();
			const diff = now - parseInt($start);
			if (diff < 10000) {
				router.get("/");
			}
		}
	});
</script>

<header />

<main>
	<h1>Loaded: {time}</h1>
	<button on:click={handleClick}>Loop it!</button>
	<h2>Count: {$count}</h2>
</main>

<style>
	a {
		display: block;
		margin-bottom: 0.25rem;
	}
</style>
